### ISSUE TITLE
Code signing fails in Xcode 10

### ISSUE THREAD

**Issue by heestand-xyz** [aleph7/Surge#97]
The lib is working fine when testing locally,
tho when I try to upload the app to AppStore to TestFlight,
I get this error:
> Code signing "Upsurge.framework" failed.

Installed via Carthage: `github "aleph7/Upsurge"`

Is the fault on my end?
Do I need to code sign the framework manually?
Currently, I'm auto code signing my code.

The log:
> 2018-06-20 11:42:36 +0000  Entitlements for <IDEDistributionItem: 0x7fb1fe13f990 'com.venturemedia.Upsurge-iOS' '<DVTFilePath:0x7fb2004e2670:'/Users/hexagons/Library/Developer/Xcode/Archives/2018-06-20/Simple 2018-06-20, 13.40.xcarchive/Products/Applications/Simple.app/Frameworks/Upsurge.framework'>'>: {
> }
> 2018-06-20 11:42:36 +0000  Writing entitlements for <IDEDistributionItem: 0x7fb1fe13f990 'com.venturemedia.Upsurge-iOS' '<DVTFilePath:0x7fb2004e2670:'/Users/hexagons/Library/Developer/Xcode/Archives/2018-06-20/Simple 2018-06-20, 13.40.xcarchive/Products/Applications/Simple.app/Frameworks/Upsurge.framework'>'> to: /var/folders/nj/sxc06r5n5sq8kspxshhr8ywc0000gn/T/XcodeDistPipeline.rkQ/entitlementsKpf3zc
> 2018-06-20 11:42:36 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'D371C962AE81A2A1E163CDD01F6295F02B2F166E' '--entitlements' '/var/folders/nj/sxc06r5n5sq8kspxshhr8ywc0000gn/T/XcodeDistPipeline.rkQ/entitlementsKpf3zc' '--preserve-metadata=identifier,flags,runtime' '/var/folders/nj/sxc06r5n5sq8kspxshhr8ywc0000gn/T/XcodeDistPipeline.rkQ/Root/Payload/Simple.app/Frameworks/Upsurge.framework'
> 2018-06-20 11:42:36 +0000  /var/folders/nj/sxc06r5n5sq8kspxshhr8ywc0000gn/T/XcodeDistPipeline.rkQ/Root/Payload/Simple.app/Frameworks/Upsurge.framework: replacing existing signature
> 2018-06-20 11:42:36 +0000  /var/folders/nj/sxc06r5n5sq8kspxshhr8ywc0000gn/T/XcodeDistPipeline.rkQ/Root/Payload/Simple.app/Frameworks/Upsurge.framework: code object is not signed at all
> 2018-06-20 11:42:36 +0000  
> 2018-06-20 11:42:36 +0000  2018-06-20 11:42:36 +0000  /usr/bin/codesign exited with 1

**Comment by pchampeau** [comment]
Did you ever find a solution to this issue? I'm facing the same problem since upgrading to Xcode 10...

**Comment by heestand-xyz** [comment]
Not really, I ended up copying all source files into my bundle to get it to work ^^

**Comment by swoltron** [comment]
I have the exact same issue with another framework installed with Carthage.  I went into manual signing and ended up at this screen (see attached picture).  When I went on to validate/distrubute I got the error "Code signing "CSVImporter.framework" failed."  The same problem happens if I use auto signing as well.

Any information on how to fix this short of copying all the source files would be very helpful.


![code signing error](https://user-images.githubusercontent.com/36624397/48682023-d4432b80-eb6b-11e8-806d-202c689cfcf3.png)
 


![no provisioning profile required](https://user-images.githubusercontent.com/36624397/48681919-1cae1980-eb6b-11e8-8dba-2b9582680461.png)
